### ISSUE TITLE
Implement race selection screen

### ISSUE THREAD

**Issue by chanulee1** [JoshPark03/DND-Companion-App#37]
- Create a working screen for the user to select the race when creating a new character.
- The input data should be parsed and stored in a database.
- The elements of the screen should be organized in a logical, easy-to-understand way.
- The screen should include buttons so the user can easily navigate between the character creation screens.
- Information about each race should be displayed.

**Comment by craig-zac-a** [comment]
There is an issue when selecting from the dropdown menu where the dropdown is drawn outside of the app causing the user to have to select the last one shown multiple times to get to the bottom if the window is maximized.
